#!/bin/bash
# Update package list and install Ansible
sudo apt-get update
sudo apt-get install -y ansible

# Git clone project to run ansible and docker compose
git clone https://github.com/Yoram-Izilov-Nitzanim/Ansible /home/ubuntu/Ansible

# change group owner back to the ubuntu user
chown -R ubuntu:ubuntu /home/ubuntu

# Run ansible
ansible-playbook /home/ubuntu/Ansible/playbook-localhost.yaml
