#!/bin/bash
# Update package list and install Ansible
sudo apt-get update
sudo apt-get install -y ansible

# Git clone project to run ansible and docker compose
git clone https://github.com/Yoram-Izilov-Nitzanim/Ansible /home/ubuntu/Ansible

# Run ansible
ansible-playbook -i /home/ubuntu/Ansible/hosts /home/ubuntu/Ansible/playbook-v2.yaml
