---
- name: Install Docker, aws-cli on Ubuntu, run docker-compose
  hosts: all
  become: true

  tasks:
    - name: Update the apt package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: yes
        
    - name: Install docker-compose
      get_url:
        url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '755'

    - name: Add user to docker group
      user:
        name: "ubuntu"
        group: docker
        append: yes

    - name: Download AWS CLI zip file
      get_url:
        url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
        dest: "/home/ubuntu/awscliv2.zip"

    - name: Install unzip package
      apt:
        name:
          - unzip
        state: present

    - name: Unzip AWS CLI package
      unarchive:
        src: "/home/ubuntu/awscliv2.zip"
        dest: "/home/ubuntu/"
        remote_src: yes

    - name: Unzip AWS CLI package
      unarchive:
        src: "/home/ubuntu/awscliv2.zip"
        dest: "/home/ubuntu/"
        remote_src: yes

    - name: Install AWS CLI
      command: "/home/ubuntu/aws/install"

    - name: Check AWS CLI version
      command: "aws --version"

    - name: Run Docker Compose
      command: docker compose -f /home/ubuntu/Ansible/docker-compose.yaml up -d
