---
- name: Install Docker, aws-cli on Ubuntu, run docker-compose
  hosts: localhost
  become: true

  tasks:
    - name: Update the apt package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker
      command: apt install -y docker.io
    
    - name: Install docker-compose
      get_url:
        url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '755'

    - name: Add user to docker group
      user:
        name: "ubuntu"
        group: docker
        append: yes

    - name: Download AWS CLI zip file
      get_url:
        url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
        dest: "./awscliv2.zip"

    - name: Install unzip package
      apt:
        name:
          - unzip
        state: present

    - name: Unzip AWS CLI package
      unarchive:
        src: "./awscliv2.zip"
        dest: "./"
        remote_src: yes

    - name: Unzip AWS CLI package
      unarchive:
        src: "./awscliv2.zip"
        dest: "./"
        remote_src: yes

    - name: Install AWS CLI
      command: "./aws/install"

    - name: Check AWS CLI version
      command: "aws --version"

    - name: Run Docker Compose
      command: docker compose -f ./Ansible/docker-compose.yaml up -d
